platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'Toothie' do

  pod 'AppCenter/Core', '~> 3.0.0'
  pod 'AppCenter/Crashes', '~> 3.0.0'
  pod 'AppCenter/Analytics', '~> 3.0.0'
  pod 'AppCenterReactNativeShared', '~> 3.0.0'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'
  pod 'Stripe', '~> 17.0.1'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  use_unimodules!

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'ToothieTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

# https://rnfirebase.io/docs/v5.x.x/installation/ios#Option-2:-Cocoapods
# If you have use_framework! in your Podfile, you might need to add in it the following code to adjust the header paths to avoid the error 'Firebase.h' file not found with <angled> include; use "quotes" instead

# post_install do |installer|
#   rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
#   rnfirebase.build_configurations.each do |config|
#     config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
#   end
# end